dankookie-4983/4983-server

src/main/java/team/dankookie/server4983/book/constant/College.java, src/main/java/team/dankookie/server4983/book/constant/Department.java, src/main/java/team/dankookie/server4983/book/domain/BookImage.java, src/main/java/team/dankookie/server4983/book/domain/Locker.java, src/main/java/team/dankookie/server4983/book/domain/UsedBook.java, src/main/java/team/dankookie/server4983/chat/constant/ContentType.java, src/main/java/team/dankookie/server4983/chat/domain/BuyerChat.java, src/main/java/team/dankookie/server4983/chat/domain/SellerChat.java, src/main/java/team/dankookie/server4983/common/domain/BaseEntity.java, src/main/java/team/dankookie/server4983/jwt/domain/RefreshToken.java, src/main/java/team/dankookie/server4983/member/constant/AccountBank.java, src/main/java/team/dankookie/server4983/member/domain/Member.java
DAN-19
- 엔티티 설계
- 엔티티에 필요한 상수 구현
=> feat: 엔티티 설계 및 enum 구현

build.gradle, src/main/java/team/dankookie/server4983/chat/config/HandlerChatConfig.java, src/main/java/team/dankookie/server4983/chat/dto/ChatRequest.java, src/main/java/team/dankookie/server4983/chat/dto/ChatResponse.java, src/main/java/team/dankookie/server4983/chat/handler/WebSocketHandler.java
-
- Socket.IO Config 설정
- Socket.IO 연결 , 해제 , 데이터 전송 로직 구현
=> feat: Socket.IO 초기 설정

Dockerfile-dev, build.gradle, src/main/resources/application-dev.yaml, src/main/resources/application-prod.yaml, src/main/resources/application.yaml
DAN-59
- jar 배포에서 docker hub를 이용한 docker 배포로 수정
- dev 서버에 docker-compose를 이용하여 grafana, prometheus 실행및 연동 테스트 완료 
http://15.165.173.111:3000/d/spring_boot_21/spring-boot-2-1-system-monitor?orgId=1&refresh=5s
위 경로로 접근해서 현재 서버 상황 모니터링 가능
grafana 로그인 정보는 jira confluence 에 있습니당:>
=> feat: dockerfile 로 배포 및 grafana, prometheus 설정

src/main/java/team/dankookie/server4983/chat/handler/ChatLogicHandler.java, src/main/java/team/dankookie/server4983/chat/handler/WebSocketHandler.java
DAN-60
- ChatLogicHandler 과 WebSocketHandler 임시로 주석 처리
=> fix: github actions 테스트 오류 해결

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/common/config/filter/JwtTokenFilter.java, src/main/java/team/dankookie/server4983/jwt/util/JwtTokenUtils.java, src/main/java/team/dankookie/server4983/member/controller/MemberChangePasswordController.java, src/main/java/team/dankookie/server4983/member/controller/MemberNicknameDuplicateController.java, src/main/java/team/dankookie/server4983/member/controller/MemberPhoneNumberController.java, src/main/java/team/dankookie/server4983/member/domain/Member.java, src/main/java/team/dankookie/server4983/member/dto/MemberPasswordChangeRequest.java, src/main/java/team/dankookie/server4983/member/dto/MemberPasswordMatchResponse.java, src/main/java/team/dankookie/server4983/member/dto/NicknameDuplicateResponse.java, src/main/java/team/dankookie/server4983/member/repository/MemberRepository.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member.html, src/test/java/team/dankookie/server4983/member/controller/MemberChangePasswordControllerTest.java, src/test/java/team/dankookie/server4983/member/controller/MemberNicknameDuplicateControllerTest.java, src/test/java/team/dankookie/server4983/member/controller/MemberPasswordControllerTest.java, src/test/java/team/dankookie/server4983/member/controller/MemberPhoneNumberControllerTest.java, src/test/java/team/dankookie/server4983/member/repository/MemberRepositoryTest.java, src/test/java/team/dankookie/server4983/member/service/MemberServiceTest.java
DAN - 41
- 마이페이지 프로필 수정 로직 구현(닉네임 중복 확인, 회원 전화번호로 인증번호 전송, 비밀번호 변경)
=> feat: 마이페이지 프로필 수정 로직 구현 

src/main/java/team/dankookie/server4983/member/dto/MemberRegisterRequest.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java
DAN-73
- 테스트 멤버 2명 추가 
- ("test" : "1234")
- ("202023604" : "1234")
=> feat: 테스트 멤버 추가 

build.gradle, src/main/java/team/dankookie/server4983/chat/handler/ChatLogicHandler.java, src/main/java/team/dankookie/server4983/chat/service/ChatService.java, src/main/java/team/dankookie/server4983/common/config/FCMConfig.java, src/main/java/team/dankookie/server4983/fcm/dto/FcmBaseRequest.java, src/main/java/team/dankookie/server4983/fcm/dto/FcmResponse.java, src/main/java/team/dankookie/server4983/fcm/dto/FcmTargetUserIdRequest.java, src/main/java/team/dankookie/server4983/fcm/service/FcmService.java, src/main/java/team/dankookie/server4983/member/domain/Member.java, src/main/java/team/dankookie/server4983/member/dto/MemberRegisterRequest.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/main/resources/static/docs/member.html, src/main/resources/static/docs/usedBook.html, src/test/java/team/dankookie/server4983/member/controller/MemberRegisterControllerTest.java
DAN-77
- FCM 연동 및 서비스 구현
- 채팅 푸쉬알람 기능 구현
- 채팅 핸들러 부분에서 반대로 작성한 것같아서 수정하였는데 한번 확인 부탁드리겠습니당
=> feat: FCM 기능 구현 및 채팅 푸쉬알람 기능 구현

src/main/java/team/dankookie/server4983/member/service/MemberService.java
DAN-79
- UsedBook 10개 데이터 추가하였습니다.
=> feat: UsedBook Mock 데이터 삽입

src/main/java/team/dankookie/server4983/jwt/domain/RefreshToken.java, src/main/java/team/dankookie/server4983/jwt/repository/RefreshTokenRepository.java, src/main/java/team/dankookie/server4983/jwt/service/RefreshTokenService.java, src/main/java/team/dankookie/server4983/member/controller/MemberLoginController.java, src/main/resources/static/docs/member.html, src/main/resources/static/docs/usedBook.html
DAN-80
refreshToken에서 member에 unique 제약 조건이 걸려있었는데 login 성공시 무조건 save 되게 만들어놓아서 수정
=> fix: refreshToken save 안되는 에러 해결

src/docs/asciidoc/usedBook.adoc, src/main/java/team/dankookie/server4983/book/controller/MyPageBookPurchaseDetailListController.java, src/main/java/team/dankookie/server4983/book/dto/MyPageBookPurchaseDetailListResponse.java, src/main/java/team/dankookie/server4983/book/repository/mypageBookPurchaseDetail/BookPurchaseDetailRepository.java, src/main/java/team/dankookie/server4983/book/repository/mypageBookPurchaseDetail/BookPurchaseDetailRepositoryCustom.java, src/main/java/team/dankookie/server4983/book/repository/mypageBookPurchaseDetail/BookPurchaseDetailRepositoryImpl.java, src/main/java/team/dankookie/server4983/book/service/MyPageBookPurchaseDetailListService.java, src/test/java/team/dankookie/server4983/book/controller/MyPageBookPurchaseDetailListControllerTest.java, src/test/java/team/dankookie/server4983/book/repository/mypageBookPurchaseDetail/BookPurchaseDetailRepositoryTest.java
=> feat: 마이페이지 구매내역 로직 구현

src/main/java/team/dankookie/server4983/book/domain/UsedBook.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java
=> Hotfix: 테스트 데이터 코드 수정

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberLogoutController.java, src/test/java/team/dankookie/server4983/member/controller/MemberLogoutControllerTest.java
=> feat: 마이페이지 로그아웃 api 구현

src/docs/asciidoc/chat.adoc, src/main/java/team/dankookie/server4983/chat/controller/ChatController.java, src/main/java/team/dankookie/server4983/chat/dto/ChatMessageResponse.java, src/main/java/team/dankookie/server4983/chat/repository/ChatRoomRepository.java, src/main/java/team/dankookie/server4983/chat/repository/ChatRoomRepositoryCustom.java, src/main/java/team/dankookie/server4983/chat/repository/ChatRoomRepositoryImpl.java, src/main/java/team/dankookie/server4983/chat/service/ChatService.java, src/main/java/team/dankookie/server4983/jwt/dto/AccessToken.java, src/main/java/team/dankookie/server4983/jwt/resolver/LoginResolver.java, src/test/java/team/dankookie/server4983/book/controller/MyPageBookPurchaseDetailListControllerTest.java, src/test/java/team/dankookie/server4983/book/controller/MyPageBookSalesDetailListControllerTest.java, src/test/java/team/dankookie/server4983/book/controller/UsedBookControllerTest.java, src/test/java/team/dankookie/server4983/book/service/UsedBookServiceTest.java, src/test/java/team/dankookie/server4983/chat/controller/ChatListControllerTest.java, src/test/java/team/dankookie/server4983/chat/repository/ChatRoomRepositoryTest.java, src/test/java/team/dankookie/server4983/member/controller/MemberReadControllerTest.java
=> hotfix: 채팅 내역 가져오는 로직 수정

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberWithdrawController.java, src/main/java/team/dankookie/server4983/member/domain/Member.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/main/resources/static/docs/member.html, src/test/java/team/dankookie/server4983/member/controller/MemberWithdrawControllerTest.java, src/test/java/team/dankookie/server4983/member/service/MemberServiceTest.java
=> feat: 마이페이지 회원탈퇴 로직 구현

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberWithdrawController.java, src/main/java/team/dankookie/server4983/member/domain/Member.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/main/resources/static/docs/chat.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member.html, src/main/resources/static/docs/usedBook.html, src/test/java/team/dankookie/server4983/member/controller/MemberWithdrawControllerTest.java, src/test/java/team/dankookie/server4983/member/service/MemberServiceTest.java
=> refactor: 마이페이지 회원탈퇴 로직 수정

src/docs/asciidoc/usedBook.adoc, src/main/java/team/dankookie/server4983/book/controller/UsedBookListController.java, src/main/java/team/dankookie/server4983/book/domain/UsedBook.java, src/main/java/team/dankookie/server4983/book/repository/usedBook/UsedBookRepositoryCustom.java, src/main/java/team/dankookie/server4983/book/repository/usedBook/UsedBookRepositoryImpl.java, src/main/java/team/dankookie/server4983/book/service/UsedBookListService.java, src/main/java/team/dankookie/server4983/chat/repository/ChatRoomRepositoryImpl.java, src/main/resources/application-dev.yaml, src/main/resources/static/docs/chat.html, src/main/resources/static/docs/index.html, src/main/resources/static/docs/member.html, src/main/resources/static/docs/usedBook.html, src/test/java/team/dankookie/server4983/book/controller/UsedBookListControllerTest.java
DAN-54
- 검색어에 따라 리스트 반환 api 구현 
=> feat: 검색어 api 구현

src/main/java/team/dankookie/server4983/book/constant/College.java, src/main/java/team/dankookie/server4983/book/constant/Department.java, src/main/resources/static/docs/chat.html, src/main/resources/static/docs/member.html, src/main/resources/static/docs/usedBook.html
DAN-96
- 단과대, 학과 enum에 교양이라는 값 추가 
데이터를 받아오는 dto가 record라 모든 값이 들어와야하기 때문에 이렇게 설계
=> feat: 단과대, 학과 enum에 교양값 추가

src/main/java/team/dankookie/server4983/book/domain/UsedBook.java, src/main/java/team/dankookie/server4983/book/dto/UsedBookListResponse.java, src/main/java/team/dankookie/server4983/book/repository/bookImage/BookImageRepositoryImpl.java, src/main/java/team/dankookie/server4983/book/repository/usedBook/UsedBookRepositoryCustom.java, src/main/java/team/dankookie/server4983/book/repository/usedBook/UsedBookRepositoryImpl.java, src/main/java/team/dankookie/server4983/book/service/UsedBookListService.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java
=> fix: queryProjections을 활용하여 queryDsl 사용 및 서브쿼리로 N+1 문제 해결

src/main/java/team/dankookie/server4983/book/domain/UsedBook.java, src/main/java/team/dankookie/server4983/scheduler/constant/ReportType.java, src/main/java/team/dankookie/server4983/scheduler/entity/AdminReport.java, src/main/java/team/dankookie/server4983/scheduler/repository/AdminReportRepository.java, src/main/java/team/dankookie/server4983/scheduler/repository/CustomSchedulerRepository.java, src/main/java/team/dankookie/server4983/scheduler/repository/SchedulerRepositoryImpl.java, src/main/java/team/dankookie/server4983/scheduler/service/AdminReportService.java, src/test/java/team/dankookie/server4983/chat/repository/SchedulerRepositoryTest.java
100
- 위험 요소 중 어드민에게 연락을 취해야 하는 정보를 알려주는 로직 구현
- 어드민 알림 정보는 scheduler.entity.AdminReport 에 있습니다.
=> feat: 어드민 보고 알림 구현 

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberUpdateController.java, src/main/java/team/dankookie/server4983/member/repository/memberImage/MemberImageRepository.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/test/java/team/dankookie/server4983/member/controller/MemberUpdateControllerTest.java
DAN-120
feat: 마이페이지 프로필 이미지 삭제 api 구현
=> feat: 마이페이지 프로필 이미지 삭제 api 구현

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberPhoneNumberDuplicateController.java, src/main/java/team/dankookie/server4983/member/dto/PhoneNumberDuplicateResponse.java, src/main/java/team/dankookie/server4983/member/repository/MemberRepository.java, src/main/java/team/dankookie/server4983/member/service/MemberService.java, src/test/java/team/dankookie/server4983/member/controller/MemberPhoneNumberDuplicateControllerTest.java
DAN - 122
feat: 마이페이지 전화번호 중복 확인 api 구현
=> feat: 마이페이지 전화번호 중복 확인 api 구현

src/docs/asciidoc/member.adoc, src/main/java/team/dankookie/server4983/member/controller/MemberMyPageController.java, src/test/java/team/dankookie/server4983/member/controller/MemberMyPageControllerTest.java
DAN-123
feat: 마이페이지 수정하기 들어갈때 비밀번호 확인 api 구현
=> feat: 마이페이지 수정하기 들어갈때 비밀번호 확인 api 구현
